### ISSUE TITLE
Add common/generic algorithms to the Algorithms folder

### ISSUE THREAD

**Issue by 4molybdenum2** [4molybdenum2/DSA#1]
Add to the algorithms folder some common/generic algorithms.
(Also add testcases for the given problems)

**Comment by harshgupta1249** [comment]
> Add to the algorithms folder some common/generic algorithms.

@4molybdenum2 Can I work on this issue ?
I will be adding the following algorithms in CPP :
Sorting : Merge Sort, Quick Sort, Count Sort,
Sieve of Eratosthenes
Two Pointer Technique

**Comment by 4molybdenum2** [comment]
> > Add to the algorithms folder some common/generic algorithms.
> 
> @4molybdenum2 Can I work on this issue ? I will be adding the following algorithms in CPP : Sorting : Merge Sort, Quick Sort, Count Sort, Sieve of Eratosthenes Two Pointer Technique

@harshgupta1249 Yea sure. Go on ahead. Although one thing to note - Two Pointer is a method to solve a problem and not necessarily an algorithm 😄

**Comment by Sanket2055** [comment]
Hello Sir , i would like to contribute some algorithms of  graph traversal (bfs and dfs)and string matching . Please allow me to go ahead / assign me this issue . Thank you!

**Comment by XDRAGON2002** [comment]
@4molybdenum2 can I contribute in python ? If so then what folder structure should I follow ? Also can I contribute data structures like Union Find and Segment Trees ? or are the contributions solely limited to algorithms ?

**Comment by 4molybdenum2** [comment]
> @4molybdenum2 can I contribute in python ? If so then what folder structure should I follow ? Also can I contribute data structures like Union Find and Segment Trees ? or are the contributions solely limited to algorithms ?

Yep sure, I was thinking that it would be better for the algorithms in a global folder so that those are easily accessible. So I guess add to that folder. And if you want to submit individual problems, then add a folder by your name and add the problems there 😄

**Comment by XDRAGON2002** [comment]
Oh okay then, I would like to contribute too in that case.

**Comment by SaahilSabu** [comment]
@4molybdenum2 hi sir i would like to add insertion and deletion algorithm for avl tree

**Comment by gurpreet-legend** [comment]
I want to contribute

**Comment by 4molybdenum2** [comment]
@SaahilSabu @gurpreet-legend  Pls go ahead. Make sure your code is well documented 😃

**Comment by kailash360** [comment]
I want to work on this issue

**Comment by gaurav879** [comment]
@4molybdenum2 Sir I would like to work on this issue.

**Comment by AmanPachori** [comment]
Hi @4molybdenum2  sir I would like to work on this 
I will adding algorithms in c++
Selection sort,Insertion sort etc

**Comment by 4molybdenum2** [comment]
Yea go ahead @gaurav879 @AmanPachori

**Comment by shikhar13012001** [comment]
Hi @4molybdenum2  is this still open. Can I work on it?

**Comment by 4molybdenum2** [comment]
yea go ahead

**Comment by AmanPachori** [comment]
@4molybdenum2  I have make PR of insertion and selection sort

**Comment by kailash360** [comment]
Can I add algorithms on Infix, Prefix, Postfix?

**Comment by shikhar13012001** [comment]
Hello sir, Can I add Binary lifting , LCA , topological sort algo? (if it does not conflict)

**Comment by gurpreet-legend** [comment]
Can I add the implementation of stack, queue, dequeue using array, circular array and by dynamic allocation by creating a separate folder names as `Implementation of Data Stuctures`

**Comment by harshgupta1249** [comment]
Can I add Stock span  and Trapping rainwater problems using stacks in dsa folder ?

**Comment by 4molybdenum2** [comment]
Please go ahead and make a PR @Sanket2055
