### ISSUE TITLE
Fix/Optimize Code for the following codes

### ISSUE THREAD

**Issue by 4molybdenum2** [4molybdenum2/DSA#2]
These problems need to be fixed according to the comments mentioned in each of them. 

- [x] **Problem Link:** https://leetcode.com/problems/distinct-subsequences/
https://github.com/4molybdenum2/DSA/blob/5281d3a1295f571d99466db8f29ee678e91862be/me/leetcode/dp/distinct_subsequences.cpp#L6-L8

https://github.com/4molybdenum2/DSA/blob/5281d3a1295f571d99466db8f29ee678e91862be/me/dsa/graph/shortest_path_dag.cpp#L1-L2

**Comment by addy0110** [comment]
For the sorted path in Directed Acyclic Graph, Can you give any test case for which it's giving segmentation fault because it worked perfectly for test cases which I considered?

**Comment by 4molybdenum2** [comment]
Hmm, as I am looking at it now, it seems that this code has some error, I don't remember exactly for what input this was causing seg. fault, but it would be great if you could update the code to make it work correctly.
